# Generated by Django 3.0.7 on 2020-06-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='content',
        ),
    ]
